package net.jordanvpn.app.core

import android.net.Uri

/**
 * A parsed `vless://` profile.
 *
 * This is the FIRST HOP only: it says how to reach a gateway, and nothing about
 * how that gateway reaches the internet. Route selection happens in the control
 * plane; the client simply uses whichever gateways the subscription currently
 * hands out.
 */
data class VlessProfile(
    /** The original `vless://` line, kept so it can be copied or shared. */
    val uri: String,
    val uuid: String,
    val host: String,
    val port: Int,
    val label: String,
    val tls: Boolean,
    val sni: String?,
    val wsPath: String,
    val wsHost: String?,
) {
    companion object {
        fun parse(uri: String): VlessProfile? {
            if (!uri.startsWith("vless://")) return null
            val parsed = Uri.parse(uri)
            val uuid = parsed.userInfo ?: return null
            val host = parsed.host ?: return null
            val port = parsed.port.takeIf { it > 0 } ?: return null
            val security = parsed.getQueryParameter("security") ?: "none"
            // Only ws is generated by the control plane today; anything else is
            // rejected rather than silently misconfigured.
            if ((parsed.getQueryParameter("type") ?: "ws") != "ws") return null
            return VlessProfile(
                uri = uri,
                uuid = uuid,
                host = host,
                port = port,
                label = parsed.fragment ?: host,
                tls = security == "tls",
                sni = parsed.getQueryParameter("sni"),
                wsPath = parsed.getQueryParameter("path") ?: "/ws",
                wsHost = parsed.getQueryParameter("host"),
            )
        }
    }
}
