import java.util.Properties

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.compose")
    id("org.jetbrains.kotlin.plugin.serialization")
}

/**
 * Release signing.
 *
 * The keystore never enters the repository. Put its details in
 * `android/keystore.properties` (git-ignored):
 *
 *     storeFile=/absolute/path/jordan-release.jks
 *     storePassword=...
 *     keyAlias=jordan
 *     keyPassword=...
 *
 * or set JORDAN_KEYSTORE / JORDAN_KEYSTORE_PASSWORD / JORDAN_KEY_ALIAS /
 * JORDAN_KEY_PASSWORD in the environment for a CI build. With neither present
 * the release build still runs and is simply left unsigned, so a debug build
 * never fails because of a missing key.
 */
val keystoreProperties = Properties().apply {
    val file = rootProject.file("keystore.properties")
    if (file.exists()) file.inputStream().use { load(it) }
}
val keystorePath: String? = (keystoreProperties.getProperty("storeFile")
    ?: System.getenv("JORDAN_KEYSTORE"))?.takeIf { it.isNotBlank() }

/**
 * The Xray runtime is not vendored here: libXray is a large native artifact
 * with its own build (see android/README.md). Build it, drop the .aar into
 * app/libs, and this build picks it up — source set and dependency together, so
 * there is no reflection and no runtime guessing. Without it the app still
 * compiles and runs, and the tunnel reports that no runtime is bundled.
 */
val xrayAars = fileTree("libs") { include("*.aar") }
val hasXrayRuntime = !xrayAars.isEmpty

android {
    namespace = "net.jordanvpn.app"
    compileSdk = 35

    defaultConfig {
        applicationId = "net.jordanvpn.app"
        minSdk = 24
        targetSdk = 35
        versionCode = 1
        versionName = "0.1.0"

        // Where the app talks to the control plane. Override per build.
        buildConfigField("String", "CONTROL_PLANE_URL", "\"https://control.cvpn.pro\"")

        // Which machines this APK carries native code for.
        //
        // The Xray runtime is Go, compiled per architecture, and gomobile builds
        // all four: two real phone architectures and two that only exist on
        // emulators. Carrying x86 doubles the download for every customer so
        // that a developer's emulator can run it — the wrong trade for an app
        // people fetch over a phone network. arm64 is every phone sold in years;
        // armeabi-v7a keeps the old ones working.
        ndk {
            abiFilters += listOf("arm64-v8a", "armeabi-v7a")
        }

        // Whether the Premium tab may open a USDT order inside the app.
        //
        // True is right for a directly distributed APK. A Google Play build must
        // set it to false: Play's payments policy does not allow selling digital
        // goods for crypto in-app, and the tab then lists the plans read-only and
        // sends the customer to the web storefront to pay.
        buildConfigField("boolean", "IN_APP_ORDERS", "true")
    }

    signingConfigs {
        // The debug key, when the build is told where to keep it.
        //
        // A debug key is generated by the toolchain and lives in the user's home
        // directory, which on a CI runner is thrown away after every run — so
        // every build would sign with a different key, and Android refuses to
        // install an update signed by a different key. Pointing the debug config
        // at a fixed file lets CI carry one key between runs, so a new APK
        // installs over the old one instead of demanding an uninstall.
        //
        // These are the published Android debug credentials, not a secret: they
        // are the same on every machine that has ever built a debug APK, and
        // they never sign a release. Unset, the toolchain's own default is used.
        System.getenv("JORDAN_DEBUG_KEYSTORE")?.takeIf { it.isNotBlank() }?.let { path ->
            getByName("debug") {
                storeFile = file(path)
                storePassword = "android"
                keyAlias = "androiddebugkey"
                keyPassword = "android"
            }
        }
        if (keystorePath != null) {
            create("release") {
                storeFile = file(keystorePath)
                storePassword = keystoreProperties.getProperty("storePassword")
                    ?: System.getenv("JORDAN_KEYSTORE_PASSWORD")
                keyAlias = keystoreProperties.getProperty("keyAlias")
                    ?: System.getenv("JORDAN_KEY_ALIAS")
                keyPassword = keystoreProperties.getProperty("keyPassword")
                    ?: System.getenv("JORDAN_KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            signingConfig = signingConfigs.findByName("release")
        }
        debug {
            applicationIdSuffix = ".debug"
            versionNameSuffix = "-debug"
        }
    }

    sourceSets["main"].java.srcDir(if (hasXrayRuntime) "src/xray/java" else "src/noxray/java")

    buildFeatures {
        compose = true
        buildConfig = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = "17" }
}

dependencies {
    if (hasXrayRuntime) implementation(xrayAars)

    implementation("androidx.core:core-ktx:1.15.0")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.7")
    implementation("androidx.activity:activity-compose:1.9.3")
    implementation(platform("androidx.compose:compose-bom:2024.12.01"))
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.security:security-crypto:1.1.0-alpha06")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0")

    debugImplementation("androidx.compose.ui:ui-tooling")

    // Unit tests run on the JVM. They cover the parts that need no device —
    // among them the icon outlines, which are parsed by the same Compose code
    // the app uses.
    testImplementation("junit:junit:4.13.2")
}
