import java.util.Properties

plugins {
    id("com.android.application")
    id("org.jetbrains.kotlin.android")
    id("org.jetbrains.kotlin.plugin.compose")
    id("org.jetbrains.kotlin.plugin.serialization")
}

/**
 * Release signing.
 *
 * The keystore never enters the repository. Put its details in
 * `android/keystore.properties` (git-ignored):
 *
 *     storeFile=/absolute/path/cvpn-release.jks
 *     storePassword=...
 *     keyAlias=cvpn
 *     keyPassword=...
 *
 * or set CVPN_KEYSTORE / CVPN_KEYSTORE_PASSWORD / CVPN_KEY_ALIAS /
 * CVPN_KEY_PASSWORD in the environment for a CI build. With neither present
 * the release build still runs and is simply left unsigned, so a debug build
 * never fails because of a missing key.
 */
val keystoreProperties = Properties().apply {
    val file = rootProject.file("keystore.properties")
    if (file.exists()) file.inputStream().use { load(it) }
}
val keystorePath: String? = (keystoreProperties.getProperty("storeFile")
    ?: System.getenv("CVPN_KEYSTORE"))?.takeIf { it.isNotBlank() }

/**
 * The Xray runtime is not vendored here: libXray is a large native artifact
 * with its own build (see android/README.md). Build it, drop the .aar into
 * app/libs, and this build picks it up — source set and dependency together, so
 * there is no reflection and no runtime guessing. Without it the app still
 * compiles and runs, and the tunnel reports that no runtime is bundled.
 */
val xrayAars = fileTree("libs") { include("*.aar") }
val hasXrayRuntime = !xrayAars.isEmpty

android {
    namespace = "pro.cvpn.app"
    compileSdk = 35

    defaultConfig {
        applicationId = "pro.cvpn.app"
        minSdk = 24
        targetSdk = 35
        versionCode = 1
        versionName = "0.1.0"

        /**
         * Where the app talks to the control plane, in the order to try.
         *
         * A list rather than one name, because one name is a single point of
         * failure for every phone that already has the app: the day it is
         * filtered, no installation can sign in, refresh a subscription or
         * learn about a new gateway — and the fix cannot be delivered either,
         * since delivering it needs the same name. Extra entries cost a domain
         * registration a year and nothing at runtime; they are only reached
         * when the one before them cannot be connected to at all.
         *
         * Buy the spares before they are needed: a domain cannot be registered
         * from inside the situation that makes it necessary.
         */
        buildConfigField(
            "String",
            "CONTROL_PLANE_URLS",
            "\"" + (System.getenv("CVPN_CONTROL_PLANE_URLS")
                ?: "https://control.cvpn.pro") + "\"",
        )

        // Whether the Premium tab may open a USDT order inside the app.
        //
        // True is right for a directly distributed APK. A Google Play build must
        // set it to false: Play's payments policy does not allow selling digital
        // goods for crypto in-app, and the tab then lists the plans read-only and
        // sends the customer to the web storefront to pay.
        buildConfigField("boolean", "IN_APP_ORDERS", "true")
    }

    signingConfigs {
        // The debug key, when the build is told where to keep it.
        //
        // A debug key is generated by the toolchain and lives in the user's home
        // directory, which on a CI runner is thrown away after every run — so
        // every build would sign with a different key, and Android refuses to
        // install an update signed by a different key. Pointing the debug config
        // at a fixed file lets CI carry one key between runs, so a new APK
        // installs over the old one instead of demanding an uninstall.
        //
        // These are the published Android debug credentials, not a secret: they
        // are the same on every machine that has ever built a debug APK, and
        // they never sign a release. Unset, the toolchain's own default is used.
        System.getenv("CVPN_DEBUG_KEYSTORE")?.takeIf { it.isNotBlank() }?.let { path ->
            getByName("debug") {
                storeFile = file(path)
                storePassword = "android"
                keyAlias = "androiddebugkey"
                keyPassword = "android"
            }
        }
        if (keystorePath != null) {
            create("release") {
                storeFile = file(keystorePath)
                storePassword = keystoreProperties.getProperty("storePassword")
                    ?: System.getenv("CVPN_KEYSTORE_PASSWORD")
                keyAlias = keystoreProperties.getProperty("keyAlias")
                    ?: System.getenv("CVPN_KEY_ALIAS")
                keyPassword = keystoreProperties.getProperty("keyPassword")
                    ?: System.getenv("CVPN_KEY_PASSWORD")
            }
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro")
            signingConfig = signingConfigs.findByName("release")
        }
        debug {
            applicationIdSuffix = ".debug"
            versionNameSuffix = "-debug"
        }
    }

    /**
     * One APK per architecture, rather than one carrying both.
     *
     * The Go runtime is the app: about 23 MB of native code per architecture,
     * against roughly 9 MB for everything written here. Shipping both in one
     * file makes every phone download a copy of the core it cannot run, over a
     * phone network, to be discarded at install. A split build produces
     * app-arm64-v8a-debug.apk and app-armeabi-v7a-debug.apk; arm64 is every
     * phone sold in years, and armeabi-v7a is there for the older ones.
     *
     * The universal APK is built as well, and deliberately. A per-architecture
     * APK is the smaller download, but it is also the one a phone can refuse;
     * the universal file installs anywhere and is the fallback to hand someone
     * whose installer will not take the split.
     *
     * This list is also what keeps the emulator architectures out. gomobile
     * builds all four, two of which only exist on emulators, and this is the
     * only place they may be named: an `abiFilters` in defaultConfig saying the
     * same thing fails the build outright, because AGP refuses to be told which
     * architectures to package in two places at once.
     */
    splits {
        abi {
            isEnable = true
            reset()
            include("arm64-v8a", "armeabi-v7a")
            isUniversalApk = true
        }
    }

    packaging {
        jniLibs {
            /**
             * The emulator architectures, kept out of every APK.
             *
             * gomobile builds four, and two of them only exist on emulators.
             * They used to be filtered by defaultConfig's abiFilters, which
             * cannot coexist with a splits block — so with splits alone the
             * universal APK quietly grew to 239 MB by packaging all four. They
             * are excluded here, which the split APKs and the universal one
             * both obey.
             */
            excludes += listOf("**/x86/**", "**/x86_64/**")
        }
    }

    sourceSets["main"].java.srcDir(if (hasXrayRuntime) "src/xray/java" else "src/noxray/java")

    buildFeatures {
        compose = true
        buildConfig = true
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = "17" }
}

dependencies {
    if (hasXrayRuntime) implementation(xrayAars)

    implementation("androidx.core:core-ktx:1.15.0")
    implementation("androidx.lifecycle:lifecycle-runtime-ktx:2.8.7")
    implementation("androidx.activity:activity-compose:1.9.3")
    implementation(platform("androidx.compose:compose-bom:2024.12.01"))
    implementation("androidx.compose.ui:ui")
    implementation("androidx.compose.material3:material3")
    implementation("androidx.compose.ui:ui-tooling-preview")
    implementation("androidx.security:security-crypto:1.1.0-alpha06")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")
    /**
     * Here for one method: OkHttpClient.Builder.dns.
     *
     * Nothing else in the app needs a second HTTP client, and the ordinary
     * request path still goes through the platform's. This is what lets the
     * fallback supply an address for a name the phone will not resolve while
     * the URL — and so the SNI and the certificate check — keeps the real host.
     */
    implementation("com.squareup.okhttp3:okhttp:4.12.0")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0")

    debugImplementation("androidx.compose.ui:ui-tooling")

    // Unit tests run on the JVM. They cover the parts that need no device —
    // among them the icon outlines, which are parsed by the same Compose code
    // the app uses.
    testImplementation("junit:junit:4.13.2")
}
